### ISSUE TITLE
Add more CSS to the project.

### ISSUE THREAD

**Issue by sbdh11** [DeltaCoderr/Covid-19-Tracker#1]
This project does have a clean background for now, but if anyone wanna work on the CSS of this page and make the `Search` button or the taskbar more fancy. Feel free to do so!

**Comment by alabo-excel** [comment]
Hello i will like to work on this project.
Will you please assign it to me?

**Comment by sbdh11** [comment]
sure!

**Comment by SantamRC** [comment]
Hey can I also work on improving the UI. Can you assign me?

**Comment by sbdh11** [comment]
yep 
Feel free to do so

**Comment by ujjwalravi** [comment]
I've also done something. Please check the pull request. Improved many functionalities.

**Comment by sbdh11** [comment]
I'll check it asap, once I get in PC

**Comment by SantamRC** [comment]
check out my PR.

**Comment by sbdh11** [comment]
Alr will do in a bit
