### ISSUE TITLE
Add null handling

### ISSUE THREAD

**Issue by pandurijal** [DeltaCoderr/Covid-19-Tracker#2]
If we write a wrong country, it should display something like "data not found", but for now, we got "Afghanistan" instead. Can I work on this issue?

<img width="1280" alt="Screenshot 2020-10-01 at 00 10 47" src="https://user-images.githubusercontent.com/12939625/94717505-9ecc1380-037a-11eb-9be0-99dbe724b4d5.png">
<img width="1280" alt="Screenshot 2020-10-01 at 00 10 57" src="https://user-images.githubusercontent.com/12939625/94717492-9a9ff600-037a-11eb-8b79-19afb4b79baa.png">

**Comment by sbdh11** [comment]
Yep

**Comment by sbdh11** [comment]
Take a look at the API btw

**Comment by pandurijal** [comment]
Aight will do. Thanks!

**Comment by sbdh11** [comment]
Closing this
